const Pizza = [{
        id: '0',
        name: 'MARGHERITA',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '350', large: '400' }],
        countInStock: 10,
        category: 'veg',
        image: 'https://www.dominos.co.in/files/items/Margherit.jpg',
        description: 'A hugely popular margherita, with a deliciously tangy single cheese topping',
    },
    {
        id: '1',
        name: 'FARM HOUSE',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '300', large: '450' }],
        countInStock: 10,
        category: 'veg',
        image: 'https://www.dominos.co.in/files/items/Farmhouse.jpg',
        description: 'A pizza that goes ballistic on veggies! Check out this mouth watering overload of crunchy, crisp capsicum, succulent mushrooms and fresh tomatoes',
    },
    {
        id: '2',
        name: 'PEPPY PANEER',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '400', large: '700' }],
        countInStock: 10,
        category: 'nonveg',
        image: 'https://www.dominos.co.in/files/items/Peppy_Paneer.jpg',
        description: 'Peeper Barbecue Chicken I cheese',
    },
    {
        id: '3',
        name: 'PEPPER BARBECUE CHICKEN',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '350', large: '400' }],
        countInStock: 10,
        category: 'nonveg',
        image: 'https://www.dominos.co.in/files/items/Pepper_Barbeque.jpg',
        description: 'Peeper Barbecue Chicken I cheese',
    },
    {
        id: '4',
        name: 'CHICKEN SAUSAGE',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '350', large: '400' }],
        countInStock: 10,
        category: 'nonveg',
        image: 'https://www.dominos.co.in/files/items/Chicken_Sausage.jpg',
        description: 'Chicken Sausage I Cheese',
    },
    {
        id: '5',
        name: 'CHICKEN GOLDEN DELIGHT',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '350', large: '400' }],
        countInStock: 10,
        category: 'nonveg',
        image: 'https://www.dominos.co.in/files/items/Chicken_Golden_Delight.jpg',
        description: 'Mmm! Barbeque chicken with a topping of golden corn loaded with extra cheese. Worth its weight in gold!',
    },
    {
        id: '6',
        name: 'NON VEG SUPREME',
        varients: ['small', 'medium', 'large'],
        prices: [{ small: '200', medium: '350', large: '400' }],
        countInStock: 10,
        category: 'nonveg',
        image: 'https://www.dominos.co.in/files/items/Non-Veg_Supreme.jpg',
        description: 'Bite into supreme delight of Black Olives, Onions, Grilled Mushrooms, Pepper BBQ Chicken, Peri-Peri Chicken, Grilled Chicken Rashers',
    }
]
export default Pizza;